spring.application.name=coordinator

logging.level.root=WARN
spring.main.banner-mode=off

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://ep-fancy-hall-ayv4zvti-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yxdv8XGUAW2O

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true